import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Navbar from '../components/navbar'
import layoutStyle from '../styles/layout.module.css'
import FuenteTexto from '../components/fuente-texto'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <FuenteTexto />
      <body className={inter.className}>
        <div className={layoutStyle.container}>
          <div className={layoutStyle.navbar}>
            <Navbar />
          </div>
          <div className={layoutStyle.flex}>
            {children}
          </div>
        </div>
      </body>
    </html>
  )
}
